# Generated by Django 4.0.6 on 2022-09-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queID', models.TextField()),
                ('queText', models.TextField()),
                ('ratingType', models.TextField()),
            ],
        ),
    ]
